/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreerBoutiqueRouteImport } from './routes/creer-boutique'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AbonnementRouteImport } from './routes/abonnement'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutProductIdRouteImport } from './routes/checkout.$productId'
import { Route as BoutiqueSlugRouteImport } from './routes/boutique.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreerBoutiqueRoute = CreerBoutiqueRouteImport.update({
  id: '/creer-boutique',
  path: '/creer-boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementRoute = AbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutProductIdRoute = CheckoutProductIdRouteImport.update({
  id: '/checkout/$productId',
  path: '/checkout/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueSlugRoute = BoutiqueSlugRouteImport.update({
  id: '/boutique/$slug',
  path: '/boutique/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRouteWithChildren
  '/clients': typeof ClientsRoute
  '/commandes': typeof CommandesRoute
  '/creer-boutique': typeof CreerBoutiqueRoute
  '/dashboard': typeof DashboardRoute
  '/marketing': typeof MarketingRoute
  '/paiements': typeof PaiementsRoute
  '/produits': typeof ProduitsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRouteWithChildren
  '/clients': typeof ClientsRoute
  '/commandes': typeof CommandesRoute
  '/creer-boutique': typeof CreerBoutiqueRoute
  '/dashboard': typeof DashboardRoute
  '/marketing': typeof MarketingRoute
  '/paiements': typeof PaiementsRoute
  '/produits': typeof ProduitsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRouteWithChildren
  '/clients': typeof ClientsRoute
  '/commandes': typeof CommandesRoute
  '/creer-boutique': typeof CreerBoutiqueRoute
  '/dashboard': typeof DashboardRoute
  '/marketing': typeof MarketingRoute
  '/paiements': typeof PaiementsRoute
  '/produits': typeof ProduitsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnement'
    | '/aide'
    | '/auth'
    | '/clients'
    | '/commandes'
    | '/creer-boutique'
    | '/dashboard'
    | '/marketing'
    | '/paiements'
    | '/produits'
    | '/auth/callback'
    | '/boutique/$slug'
    | '/checkout/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnement'
    | '/aide'
    | '/auth'
    | '/clients'
    | '/commandes'
    | '/creer-boutique'
    | '/dashboard'
    | '/marketing'
    | '/paiements'
    | '/produits'
    | '/auth/callback'
    | '/boutique/$slug'
    | '/checkout/$productId'
  id:
    | '__root__'
    | '/'
    | '/abonnement'
    | '/aide'
    | '/auth'
    | '/clients'
    | '/commandes'
    | '/creer-boutique'
    | '/dashboard'
    | '/marketing'
    | '/paiements'
    | '/produits'
    | '/auth/callback'
    | '/boutique/$slug'
    | '/checkout/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementRoute: typeof AbonnementRoute
  AideRoute: typeof AideRoute
  AuthRoute: typeof AuthRouteWithChildren
  ClientsRoute: typeof ClientsRoute
  CommandesRoute: typeof CommandesRoute
  CreerBoutiqueRoute: typeof CreerBoutiqueRoute
  DashboardRoute: typeof DashboardRoute
  MarketingRoute: typeof MarketingRoute
  PaiementsRoute: typeof PaiementsRoute
  ProduitsRoute: typeof ProduitsRoute
  BoutiqueSlugRoute: typeof BoutiqueSlugRoute
  CheckoutProductIdRoute: typeof CheckoutProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creer-boutique': {
      id: '/creer-boutique'
      path: '/creer-boutique'
      fullPath: '/creer-boutique'
      preLoaderRoute: typeof CreerBoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement': {
      id: '/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$productId': {
      id: '/checkout/$productId'
      path: '/checkout/$productId'
      fullPath: '/checkout/$productId'
      preLoaderRoute: typeof CheckoutProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/$slug': {
      id: '/boutique/$slug'
      path: '/boutique/$slug'
      fullPath: '/boutique/$slug'
      preLoaderRoute: typeof BoutiqueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementRoute: AbonnementRoute,
  AideRoute: AideRoute,
  AuthRoute: AuthRouteWithChildren,
  ClientsRoute: ClientsRoute,
  CommandesRoute: CommandesRoute,
  CreerBoutiqueRoute: CreerBoutiqueRoute,
  DashboardRoute: DashboardRoute,
  MarketingRoute: MarketingRoute,
  PaiementsRoute: PaiementsRoute,
  ProduitsRoute: ProduitsRoute,
  BoutiqueSlugRoute: BoutiqueSlugRoute,
  CheckoutProductIdRoute: CheckoutProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
